### PR TITLE
enhancement: optionally use the leaf, not full path, of attached files

### PR DESCRIPTION
**Pull request by moltenform**

### CODE REVIEW

**Comment by ssato** [comment]
Sorry to late.

LGTM almost but I feel that 'path_names_only' is a bit long and how about to use something shorter named option such like 'basename' instead?

If you're OK, I'll merge your changes once first because I'm late and change that option later.

**Comment by moltenform** [comment]
No worries. I've renamed it to "usebasename".

**Comment by moltenform** [comment]
One of the lines was too long -- but looks like everything's passing now!

**Comment by ssato** [comment]
LGTM and merged. Thanks a lot for your effort!

**Pull request merged**
